// Auto-generated by scripts/generate-docs-index.ts - DO NOT EDIT

import bashToolRuntimeMd from "../../../../docs/bash-tool-runtime.md" with { type: "text" };
import blobArtifactArchitectureMd from "../../../../docs/blob-artifact-architecture.md" with { type: "text" };
import compactionMd from "../../../../docs/compaction.md" with { type: "text" };
import configUsageMd from "../../../../docs/config-usage.md" with { type: "text" };
import customToolsMd from "../../../../docs/custom-tools.md" with { type: "text" };
import environmentVariablesMd from "../../../../docs/environment-variables.md" with { type: "text" };
import extensionLoadingMd from "../../../../docs/extension-loading.md" with { type: "text" };
import extensionsMd from "../../../../docs/extensions.md" with { type: "text" };
import fsScanCacheArchitectureMd from "../../../../docs/fs-scan-cache-architecture.md" with { type: "text" };
import geminiManifestExtensionsMd from "../../../../docs/gemini-manifest-extensions.md" with { type: "text" };
import handoffGenerationPipelineMd from "../../../../docs/handoff-generation-pipeline.md" with { type: "text" };
import hooksMd from "../../../../docs/hooks.md" with { type: "text" };
import mcpProtocolTransportsMd from "../../../../docs/mcp-protocol-transports.md" with { type: "text" };
import mcpRuntimeLifecycleMd from "../../../../docs/mcp-runtime-lifecycle.md" with { type: "text" };
import mcpServerToolAuthoringMd from "../../../../docs/mcp-server-tool-authoring.md" with { type: "text" };
import modelsMd from "../../../../docs/models.md" with { type: "text" };
import nativesAddonLoaderRuntimeMd from "../../../../docs/natives-addon-loader-runtime.md" with { type: "text" };
import nativesArchitectureMd from "../../../../docs/natives-architecture.md" with { type: "text" };
import nativesBindingContractMd from "../../../../docs/natives-binding-contract.md" with { type: "text" };
import nativesBuildReleaseDebuggingMd from "../../../../docs/natives-build-release-debugging.md" with { type: "text" };
import nativesMediaSystemUtilsMd from "../../../../docs/natives-media-system-utils.md" with { type: "text" };
import nativesRustTaskCancellationMd from "../../../../docs/natives-rust-task-cancellation.md" with { type: "text" };
import nativesShellPtyProcessMd from "../../../../docs/natives-shell-pty-process.md" with { type: "text" };
import nativesTextSearchPipelineMd from "../../../../docs/natives-text-search-pipeline.md" with { type: "text" };
import nonCompactionRetryPolicyMd from "../../../../docs/non-compaction-retry-policy.md" with { type: "text" };
import notebookToolRuntimeMd from "../../../../docs/notebook-tool-runtime.md" with { type: "text" };
import pluginManagerInstallerPlumbingMd from "../../../../docs/plugin-manager-installer-plumbing.md" with { type: "text" };
import portingFromPiMonoMd from "../../../../docs/porting-from-pi-mono.md" with { type: "text" };
import portingToNativesMd from "../../../../docs/porting-to-natives.md" with { type: "text" };
import providerStreamingInternalsMd from "../../../../docs/provider-streaming-internals.md" with { type: "text" };
import pythonReplMd from "../../../../docs/python-repl.md" with { type: "text" };
import rpcMd from "../../../../docs/rpc.md" with { type: "text" };
import rulebookMatchingPipelineMd from "../../../../docs/rulebook-matching-pipeline.md" with { type: "text" };
import sdkMd from "../../../../docs/sdk.md" with { type: "text" };
import secretsMd from "../../../../docs/secrets.md" with { type: "text" };
import sessionMd from "../../../../docs/session.md" with { type: "text" };
import sessionOperationsExportShareForkResumeMd from "../../../../docs/session-operations-export-share-fork-resume.md" with { type: "text" };
import sessionSwitchingAndRecentListingMd from "../../../../docs/session-switching-and-recent-listing.md" with { type: "text" };
import sessionTreePlanMd from "../../../../docs/session-tree-plan.md" with { type: "text" };
import skillsMd from "../../../../docs/skills.md" with { type: "text" };
import slashCommandInternalsMd from "../../../../docs/slash-command-internals.md" with { type: "text" };
import taskAgentDiscoveryMd from "../../../../docs/task-agent-discovery.md" with { type: "text" };
import themeMd from "../../../../docs/theme.md" with { type: "text" };
import treeMd from "../../../../docs/tree.md" with { type: "text" };
import ttsrInjectionLifecycleMd from "../../../../docs/ttsr-injection-lifecycle.md" with { type: "text" };
import tuiMd from "../../../../docs/tui.md" with { type: "text" };
import tuiRuntimeInternalsMd from "../../../../docs/tui-runtime-internals.md" with { type: "text" };

export const EMBEDDED_DOCS: Readonly<Record<string, string>> = {
	"bash-tool-runtime.md": bashToolRuntimeMd,
	"blob-artifact-architecture.md": blobArtifactArchitectureMd,
	"compaction.md": compactionMd,
	"config-usage.md": configUsageMd,
	"custom-tools.md": customToolsMd,
	"environment-variables.md": environmentVariablesMd,
	"extension-loading.md": extensionLoadingMd,
	"extensions.md": extensionsMd,
	"fs-scan-cache-architecture.md": fsScanCacheArchitectureMd,
	"gemini-manifest-extensions.md": geminiManifestExtensionsMd,
	"handoff-generation-pipeline.md": handoffGenerationPipelineMd,
	"hooks.md": hooksMd,
	"mcp-protocol-transports.md": mcpProtocolTransportsMd,
	"mcp-runtime-lifecycle.md": mcpRuntimeLifecycleMd,
	"mcp-server-tool-authoring.md": mcpServerToolAuthoringMd,
	"models.md": modelsMd,
	"natives-addon-loader-runtime.md": nativesAddonLoaderRuntimeMd,
	"natives-architecture.md": nativesArchitectureMd,
	"natives-binding-contract.md": nativesBindingContractMd,
	"natives-build-release-debugging.md": nativesBuildReleaseDebuggingMd,
	"natives-media-system-utils.md": nativesMediaSystemUtilsMd,
	"natives-rust-task-cancellation.md": nativesRustTaskCancellationMd,
	"natives-shell-pty-process.md": nativesShellPtyProcessMd,
	"natives-text-search-pipeline.md": nativesTextSearchPipelineMd,
	"non-compaction-retry-policy.md": nonCompactionRetryPolicyMd,
	"notebook-tool-runtime.md": notebookToolRuntimeMd,
	"plugin-manager-installer-plumbing.md": pluginManagerInstallerPlumbingMd,
	"porting-from-pi-mono.md": portingFromPiMonoMd,
	"porting-to-natives.md": portingToNativesMd,
	"provider-streaming-internals.md": providerStreamingInternalsMd,
	"python-repl.md": pythonReplMd,
	"rpc.md": rpcMd,
	"rulebook-matching-pipeline.md": rulebookMatchingPipelineMd,
	"sdk.md": sdkMd,
	"secrets.md": secretsMd,
	"session.md": sessionMd,
	"session-operations-export-share-fork-resume.md": sessionOperationsExportShareForkResumeMd,
	"session-switching-and-recent-listing.md": sessionSwitchingAndRecentListingMd,
	"session-tree-plan.md": sessionTreePlanMd,
	"skills.md": skillsMd,
	"slash-command-internals.md": slashCommandInternalsMd,
	"task-agent-discovery.md": taskAgentDiscoveryMd,
	"theme.md": themeMd,
	"tree.md": treeMd,
	"ttsr-injection-lifecycle.md": ttsrInjectionLifecycleMd,
	"tui.md": tuiMd,
	"tui-runtime-internals.md": tuiRuntimeInternalsMd,
};

export const EMBEDDED_DOC_FILENAMES = Object.keys(EMBEDDED_DOCS).sort();
